<?php
// module/Album/view/addresses/addresses/index.phtml:

$title = 'Adresacja MSWS';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('addresses', array('action'=>'add'));?>">Add new addresses</a>
</p>

<table class="table">
<tr>
    <th>Adres IP</th>
    <th>Host</th>
    <th>Description</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($addresses as $address) : ?>
<tr>
    <td><?php echo $this->escapeHtml($address->ipaddress);?></td>
    <td><?php echo $this->escapeHtml($address->hostname);?></td>
    <td><?php echo $this->escapeHtml($address->description);?></td>
    <td>
        <a href="<?php echo $this->url('addresses',
            array('action'=>'edit', 'id' => $address->id));?>">Edit</a>
        <a href="<?php echo $this->url('addresses',
            array('action'=>'delete', 'id' => $address->id));?>">Delete</a>
    </td>
</tr>
<?php endforeach; ?>
</table>